### ISSUE TITLE
[Bug] Fonts do not match in the EN/BG pages

### ISSUE THREAD

**Issue by atomov93** [daritelska-platforma/frontend#183] opened 2021-05-06 11:39 UTC
**Describe the bug**
The fonts are different in the different languages.

I will create a separate bug for each language but this is the summary of this bug.

**To Reproduce**

1. Go to 'https://dev1.podkrepi.bg/about' and 'https://dev1.podkrepi.bg/en/about'
2. Switch languages
3. See error

I can't see what exactly is wrong but the styles are different. Please refer to the screenshots. I have been trying for 2 hours now to see the CSS problem.

**Expected behavior**
Same Font.

**Screenshots**
BG:
![image](https://user-images.githubusercontent.com/62711773/117291829-254c5480-ae78-11eb-9b4f-5d73c6ac305c.png)

EN:
![image](https://user-images.githubusercontent.com/62711773/117291867-2ed5bc80-ae78-11eb-905b-de49022dfb3d.png)

**Desktop (please complete the following information):**

- OS: MacOS BigSur
- Browser Opera GX
- Version 73.0.3856.438

**Smartphone (please complete the following information):**

- Device: iPhone 11 Pro Max
- OS: iOS 14.5.1
- Browser Safari

BG
![IMG_5570](https://user-images.githubusercontent.com/62711773/117292323-c1765b80-ae78-11eb-9ff1-abf52e3df878.PNG)

EN
![IMG_5571](https://user-images.githubusercontent.com/62711773/117292334-c3d8b580-ae78-11eb-8c1e-f276959e209f.PNG)

**Comment by kachar** [comment] 2021-05-07 06:19
Duplicate of https://github.com/daritelska-platforma/frontend/issues/165

**Closed** 2021-05-07 06:21 UTC
Labels: bug
