### ISSUE TITLE
[Bug]https://dev1.podkrepi.bg/en/about leads to bulgarian text

### ISSUE THREAD

**Issue by atomov93** [daritelska-platforma/frontend#182] opened 2021-05-06 11:16 UTC
**Describe the bug**
The about page when in English is in Bulgarian.

**To Reproduce**

1. Go to 'https://dev1.podkrepi.bg/en/about'
2. See error

**Expected behavior**
English page

**Comment by kachar** [comment] 2021-05-07 06:18
Duplicate of https://github.com/daritelska-platforma/frontend/issues/165

**Comment by atomov93** [comment] 2021-05-07 06:22
Not the same. The page is not translated. #165 is font changes.

**Closed** 2021-05-07 08:04 UTC
Labels: bug
