### ISSUE TITLE
[Bug] Fonts are different in the Home Page in both languages

### ISSUE THREAD

**Issue by atomov93** [daritelska-platforma/frontend#184] opened 2021-05-06 11:43 UTC
**Describe the bug**
Fonts of Headers and Paragraphs are different.

Headers are Montserat
Paragraphs are Roboto

**To Reproduce**

1. Go to 'https://dev1.podkrepi.bg/en' and 'https://dev1.podkrepi.bg/'
2. Click on 'Inspect Element' first on the header and then on the paragraph
3. See error

**Expected behavior**
Same font

**Screenshots**
Header:
![image](https://user-images.githubusercontent.com/62711773/117292930-6db84200-ae79-11eb-941d-e7c42545ef8c.png)

Paragraph:
![image](https://user-images.githubusercontent.com/62711773/117292882-5da06280-ae79-11eb-9d0b-d60b30f55337.png)

**Comment by kachar** [comment] 2021-05-07 06:19
Duplicate of https://github.com/daritelska-platforma/frontend/issues/165

**Closed** 2021-05-07 06:20 UTC
Labels: bug
